import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import { compareDesc } from "date-fns";
import {
  allBlogEnUs,
  allBlogPtBRs,
  allNewsletters,
} from "contentlayer/generated";
import { DatePost } from "@lib/utils";
import Navbar from "@components/Navbar";
import Container from "@components/Container";

export function getStaticProps({ locale }: { locale: string }) {
  const postLang = locale === "pt-BR" ? allBlogPtBRs : allBlogEnUs;
  const posts = postLang
    .sort((a, b) => {
      return compareDesc(new Date(a.date), new Date(b.date));
    })
    .slice(0, 4);

  return { props: { posts } };
}

const Home = ({ posts }: any) => {
  const router = useRouter();
  const { locale } = router;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar locale={locale} />

      <Container>
        {posts.map((post: any, index: any) => (
          <Link
            key={index}
            href={`blog/${post.slug}`}
            locale={locale as string}
            className="hover:opacity-60 transition-opacity"
          >
            <>
              <h3 className="text-neutral-900 dark:text-neutral-300">
                {post.title}
              </h3>
              <span className="text-neutral-800 dark:text-neutral-400">
                {DatePost(post.date, locale as string)}
              </span>
            </>
          </Link>
        ))}
      </Container>
    </>
  );
};

export default Home;
